version: '3'
services:
  music:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      active: release
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /mnt/music/log:/var/log
      - /home/data:/data
    command: [
        'java',
        '-Xmx500m',
        '-jar',
        '/opt/app.jar'
    ]
    networks:
      default:
        ipv4_address: 172.18.0.12
networks:
  default:
    external:
      name: mynetwork
