cache:
  leveldb:
    path: /data/db
app:
  gateway: http://www.kuwo.cn
  path: /data/music
spring:
  redis:
    port: 6379
    host: test.tb.xqcrm.com
    password: test_redis_pa
server:
  port: 8008
