package com.huanxi.music;

import com.alibaba.fastjson.JSON;
import com.huanxi.music.nosql.ICache;
import com.huanxi.music.onedrive.OneDriveService;
import com.huanxi.music.onedrive.TokenBean;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import javax.annotation.Resource;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * @author huanxi
 * @date 2020/4/21 5:41 下午
 * @email 1355473748@qq.com
 */
@SpringBootTest
public class TestOneDrive {

    @Resource
    OneDriveService service;
    @Resource
    ICache cache;
    @Test
    public void test() throws IOException {
//        cache.set("test","eyJ0eXAiOiJKV1QiLCJub25jZSI6IkJ4ZFNURTVDYy1ib3BFa2lfQWVXMGtEZWVDWkxzSFlub0MtNkNuYkw2aTgiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC82ODI2NmZjMi0xMzVjLTRjMDktYmJmYi02ODQzNDliMTI5NzMvIiwiaWF0IjoxNTg3NDc0OTAxLCJuYmYiOjE1ODc0NzQ5MDEsImV4cCI6MTU4NzQ3ODgwMSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyZGdZTkRRY3BBcThNa0pQakJQZGMwYjNsMVhMM3p5NzJYK1ZqQlJRR25HeTlkTkhnb0EiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6Im11c2ljIiwiYXBwaWQiOiJiNzk3YjRlZC1lMGJjLTRmMTYtOGMyOS0xYzNlNjhlN2E4N2EiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6InhoIiwiZ2l2ZW5fbmFtZSI6InMiLCJpcGFkZHIiOiIxMTIuOTYuOTkuMTY5IiwibmFtZSI6InhocyIsIm9pZCI6ImUwZTI3MzkwLWVlNDctNDkyZS1hYmQ3LTE0MWNiM2M1OTI0YiIsInBsYXRmIjoiNSIsInB1aWQiOiIxMDAzMjAwMEFBNDg3OUVFIiwic2NwIjoiRmlsZXMuUmVhZCBGaWxlcy5SZWFkLkFsbCBwcm9maWxlIG9wZW5pZCBlbWFpbCIsInN1YiI6ImdxSFV0bUxEekNCeWlPTG5oZWRrX0w3Qk9LNWU3UFZ4czh1SnZDTFptZEUiLCJ0aWQiOiI2ODI2NmZjMi0xMzVjLTRjMDktYmJmYi02ODQzNDliMTI5NzMiLCJ1bmlxdWVfbmFtZSI6Imh4LW11c2ljQG9kLm9iYWdnLmNvbSIsInVwbiI6Imh4LW11c2ljQG9kLm9iYWdnLmNvbSIsInV0aSI6InJ6b1FJdW1NZEVDdkI0S0xqR1JaQUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfc3QiOnsic3ViIjoiaUl5aXVZRjFvc3NFdG1CUXY3OHo0YkxycDhBT3JCd0RVeDFJZWxmUVhzOCJ9LCJ4bXNfdGNkdCI6MTUzNDc1NzQzMX0.Mkqf904ejrmHXO2L6NQjxbTuCBjFO7iaPKqajVt-FBJPQUUCwAuyP8-bDpRLPRCMHUQAv9k3glrm18YE_msKhiSFP8Nnl4Ld_r7v9aQdrdZlkZcmVG3BB542hzvAmXle6ZPw-ircu4gZMcv2YgclXa-HfJdtTUgD-iy4Nudu3pQcRJNYlHQslwR7dsEAG_dpeFGN_vDKsDfNAxwlsxuyqKh0A-77P6nyeSs_KeWwmNirluETdIEXOIA2Gc5s0vHd61e0XyYgHHxwuMDBrUN61sz6Xk63U9WtK8y8XIsP2k8u8PzTDOR2dlAIZFXvEf8DKMLRXrjIoTQQSCZMAecytA");
//        System.out.println("eyJ0eXAiOiJKV1QiLCJub25jZSI6IkJ4ZFNURTVDYy1ib3BFa2lfQWVXMGtEZWVDWkxzSFlub0MtNkNuYkw2aTgiLCJhbGciOiJSUzI1NiIsIng1dCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSIsImtpZCI6IllNRUxIVDBndmIwbXhvU0RvWWZvbWpxZmpZVSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC82ODI2NmZjMi0xMzVjLTRjMDktYmJmYi02ODQzNDliMTI5NzMvIiwiaWF0IjoxNTg3NDc0OTAxLCJuYmYiOjE1ODc0NzQ5MDEsImV4cCI6MTU4NzQ3ODgwMSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IjQyZGdZTkRRY3BBcThNa0pQakJQZGMwYjNsMVhMM3p5NzJYK1ZqQlJRR25HeTlkTkhnb0EiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6Im11c2ljIiwiYXBwaWQiOiJiNzk3YjRlZC1lMGJjLTRmMTYtOGMyOS0xYzNlNjhlN2E4N2EiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6InhoIiwiZ2l2ZW5fbmFtZSI6InMiLCJpcGFkZHIiOiIxMTIuOTYuOTkuMTY5IiwibmFtZSI6InhocyIsIm9pZCI6ImUwZTI3MzkwLWVlNDctNDkyZS1hYmQ3LTE0MWNiM2M1OTI0YiIsInBsYXRmIjoiNSIsInB1aWQiOiIxMDAzMjAwMEFBNDg3OUVFIiwic2NwIjoiRmlsZXMuUmVhZCBGaWxlcy5SZWFkLkFsbCBwcm9maWxlIG9wZW5pZCBlbWFpbCIsInN1YiI6ImdxSFV0bUxEekNCeWlPTG5oZWRrX0w3Qk9LNWU3UFZ4czh1SnZDTFptZEUiLCJ0aWQiOiI2ODI2NmZjMi0xMzVjLTRjMDktYmJmYi02ODQzNDliMTI5NzMiLCJ1bmlxdWVfbmFtZSI6Imh4LW11c2ljQG9kLm9iYWdnLmNvbSIsInVwbiI6Imh4LW11c2ljQG9kLm9iYWdnLmNvbSIsInV0aSI6InJ6b1FJdW1NZEVDdkI0S0xqR1JaQUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfc3QiOnsic3ViIjoiaUl5aXVZRjFvc3NFdG1CUXY3OHo0YkxycDhBT3JCd0RVeDFJZWxmUVhzOCJ9LCJ4bXNfdGNkdCI6MTUzNDc1NzQzMX0.Mkqf904ejrmHXO2L6NQjxbTuCBjFO7iaPKqajVt-FBJPQUUCwAuyP8-bDpRLPRCMHUQAv9k3glrm18YE_msKhiSFP8Nnl4Ld_r7v9aQdrdZlkZcmVG3BB542hzvAmXle6ZPw-ircu4gZMcv2YgclXa-HfJdtTUgD-iy4Nudu3pQcRJNYlHQslwR7dsEAG_dpeFGN_vDKsDfNAxwlsxuyqKh0A-77P6nyeSs_KeWwmNirluETdIEXOIA2Gc5s0vHd61e0XyYgHHxwuMDBrUN61sz6Xk63U9WtK8y8XIsP2k8u8PzTDOR2dlAIZFXvEf8DKMLRXrjIoTQQSCZMAecytA".equals(cache.get("test")));
        long time = System.currentTimeMillis();
        System.out.println(service.getDownLoadLink("test.txt"));
        System.out.println("耗时:"+(System.currentTimeMillis()-time)+"ms");
    }
}
